/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package elevatorSim;

public class Request extends javax.swing.JFrame {
    
    private ElevatorController controller;

   
    public Request() {
        initComponents();
    }

    // Set Controller
    public void setController(ElevatorController c) {
        this.controller = c;
        /**
         * Creates new form Request
         */    

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFloor1 = new javax.swing.JButton();
        btnFloor2 = new javax.swing.JButton();
        btnFloor3 = new javax.swing.JButton();
        btnFloor4 = new javax.swing.JButton();
        btnFloor5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        floorText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFloor1.setText("1");
        btnFloor1.addActionListener(this::btnFloor1ActionPerformed);

        btnFloor2.setText("2");
        btnFloor2.addActionListener(this::btnFloor2ActionPerformed);

        btnFloor3.setText("3");
        btnFloor3.addActionListener(this::btnFloor3ActionPerformed);

        btnFloor4.setText("4");
        btnFloor4.addActionListener(this::btnFloor4ActionPerformed);

        btnFloor5.setText("5");
        btnFloor5.addActionListener(this::btnFloor5ActionPerformed);

        floorText.setEditable(false);
        floorText.setColumns(20);
        floorText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        floorText.setLineWrap(true);
        floorText.setRows(5);
        jScrollPane1.setViewportView(floorText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFloor1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFloor5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnFloor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFloor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFloor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFloor5)
                .addGap(18, 18, 18)
                .addComponent(btnFloor4)
                .addGap(18, 18, 18)
                .addComponent(btnFloor3)
                .addGap(18, 18, 18)
                .addComponent(btnFloor2)
                .addGap(18, 18, 18)
                .addComponent(btnFloor1)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFloor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloor1ActionPerformed
        controller.handleFloorRequest(1);
    }//GEN-LAST:event_btnFloor1ActionPerformed

    private void btnFloor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloor2ActionPerformed
        controller.handleFloorRequest(2);
    }//GEN-LAST:event_btnFloor2ActionPerformed

    private void btnFloor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloor3ActionPerformed
        controller.handleFloorRequest(3);
    }//GEN-LAST:event_btnFloor3ActionPerformed

    private void btnFloor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloor4ActionPerformed
        controller.handleFloorRequest(4);
    }//GEN-LAST:event_btnFloor4ActionPerformed

    private void btnFloor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloor5ActionPerformed
        controller.handleFloorRequest(5);
    }//GEN-LAST:event_btnFloor5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // (Keep the automatically generated Look and Feel code here)

    /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                // This is the specific order needed to "wake up" the logic
                Building b = new Building();
                Elevator e = new Elevator(b);
                Request gui = new Request();
                ElevatorController c = new ElevatorController(e, gui);

                gui.setController(c);
                gui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFloor1;
    private javax.swing.JButton btnFloor2;
    private javax.swing.JButton btnFloor3;
    private javax.swing.JButton btnFloor4;
    private javax.swing.JButton btnFloor5;
    private javax.swing.JTextArea floorText;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
public void updateDisplay(String message) {
    floorText.append(message);
}

    }
